language: go

go:
  - 1.4
  - 1.5
  - 1.6

install:
  - make setup-ci

script:
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile coverage-all.out -service=travis-ci

notifications:
  email: false
